[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd ekin-app && npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd ekin-app && npm run build"]

[start]
cmd = "cd ekin-app && npm start"
