[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd ekin-app && npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd ekin-app && npm run build"]

[start]
cmd = "cd ekin-app && npm start"
