[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["cd ekin-app && npm install"]

[phases.build]
cmds = ["cd ekin-app && npm run build"]

[start]
cmd = "cd ekin-app && npm start"
